/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemabancario.view;

import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import sistemabancario.view.tables.TabelaPagamento;
import sistemabancario.controller.ControllerPagamento;
import sistemabancario.exception.PagamentoException;
import sistemabancario.utils.GerarMensagens;


/**
 *
 * @author alunos
 */
public class TelaCadastroPagamento extends javax.swing.JDialog {

    /**
     * Creates new form TelaCadastroPagamento
     */
   

  public TelaCadastroPagamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListaPagamentos = new javax.swing.JTable();
        txtPesquisaClientePagamento = new javax.swing.JTextField();
        btnNovoPagamento = new javax.swing.JButton();
        btnExcluirPagamento = new javax.swing.JButton();
        btnPesquisarPorCpf = new javax.swing.JButton();
        btnPesquisaGeral = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelaListaPagamentos.setModel(new TabelaPagamento());
        jScrollPane1.setViewportView(tabelaListaPagamentos);

        txtPesquisaClientePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaClientePagamentoActionPerformed(evt);
            }
        });

        btnNovoPagamento.setText("Novo Pagamento");
        btnNovoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPagamentoActionPerformed(evt);
            }
        });

        btnExcluirPagamento.setText("Excluír");
        btnExcluirPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPagamentoActionPerformed(evt);
            }
        });

        btnPesquisarPorCpf.setText("Pesquisar");
        btnPesquisarPorCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPorCpfActionPerformed(evt);
            }
        });

        btnPesquisaGeral.setText("Pesquisa Geral");
        btnPesquisaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaGeralActionPerformed(evt);
            }
        });

        jLabel2.setText("Pesquisa por Cpf:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnPesquisaGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(btnNovoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(btnExcluirPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPesquisaClientePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnPesquisarPorCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPesquisaClientePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarPorCpf))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisaGeral)
                    .addComponent(btnNovoPagamento)
                    .addComponent(btnExcluirPagamento))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPagamentoActionPerformed
      var controller = new ControllerPagamento();
        try {
            controller.excluirPagamento(this);
        } catch (PagamentoException ex) {
            GerarMensagens.erro(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnExcluirPagamentoActionPerformed

    private void btnNovoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPagamentoActionPerformed
        var TelaNovoPagamento = new TelaNovoPagamento(this, true);
        TelaNovoPagamento.setVisible(true);
    }//GEN-LAST:event_btnNovoPagamentoActionPerformed

    private void btnPesquisarPorCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPorCpfActionPerformed
     var controller = new ControllerPagamento();
        controller.pesquisar(this);
    }//GEN-LAST:event_btnPesquisarPorCpfActionPerformed

    private void btnPesquisaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaGeralActionPerformed
       var controller = new ControllerPagamento();
        controller.pesquisarTodos(this);
    }//GEN-LAST:event_btnPesquisaGeralActionPerformed

    private void txtPesquisaClientePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaClientePagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaClientePagamentoActionPerformed

    public JTable getTabelaListaPagamentos() {
        return tabelaListaPagamentos;
    }

    public JTextField getTxtPesquisaClientePagamento() {
        return txtPesquisaClientePagamento;
    }


    
    
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroPagamento dialog = new TelaCadastroPagamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirPagamento;
    private javax.swing.JButton btnNovoPagamento;
    private javax.swing.JButton btnPesquisaGeral;
    private javax.swing.JButton btnPesquisarPorCpf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaListaPagamentos;
    private javax.swing.JTextField txtPesquisaClientePagamento;
    // End of variables declaration//GEN-END:variables
}
