/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sistemabancario.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import sistemabancario.controller.ControllerAgencia;
import sistemabancario.exception.AgenciaException;
import sistemabancario.utils.GerarMensagens;
import sistemabancario.view.tables.TabelaAgencia;

/**
 *
 * @author alunos
 */
public class TelaCadastroAgencia extends javax.swing.JDialog {

    /**
     * Creates new form TelaCadastroAgencia
     */
    public TelaCadastroAgencia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public JTable getTableListaAgencia() {
        return tableListaAgencia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoNovaAgencia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListaAgencia = new javax.swing.JTable();
        botaoAtualizaListaAgencia = new javax.swing.JButton();
        botaoEditarAgencia = new javax.swing.JButton();
        botaoExcluirAgencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botaoNovaAgencia.setText("Nova Agência");
        botaoNovaAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovaAgenciaActionPerformed(evt);
            }
        });

        tableListaAgencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableListaAgencia.setModel(new TabelaAgencia());
        tableListaAgencia.getColumnModel().getColumn(0).setPreferredWidth(250);
        tableListaAgencia.getColumnModel().getColumn(1).setPreferredWidth(250);
        tableListaAgencia.getColumnModel().getColumn(2).setPreferredWidth(260);
        //tableListaAgencia.getColumnModel().getColumn(3).setPreferredWidth(200);
        tableListaAgencia.setName(""); // NOI18N
        jScrollPane1.setViewportView(tableListaAgencia);

        botaoAtualizaListaAgencia.setText("Atualizar");
        botaoAtualizaListaAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizaListaAgenciaActionPerformed(evt);
            }
        });

        botaoEditarAgencia.setText("Editar");
        botaoEditarAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarAgenciaActionPerformed(evt);
            }
        });

        botaoExcluirAgencia.setText("Excluir");
        botaoExcluirAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirAgenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(botaoAtualizaListaAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(botaoNovaAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(botaoEditarAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(botaoExcluirAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoNovaAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAtualizaListaAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEditarAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExcluirAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovaAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovaAgenciaActionPerformed
        var TelaNovaAgencia = new TelaNovaAgencia(this, true);
        TelaNovaAgencia.setVisible(true);
    }//GEN-LAST:event_botaoNovaAgenciaActionPerformed

    private void botaoAtualizaListaAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizaListaAgenciaActionPerformed
        var controller = new ControllerAgencia();
        controller.pesquisar(this);
    }//GEN-LAST:event_botaoAtualizaListaAgenciaActionPerformed

    private void botaoEditarAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarAgenciaActionPerformed

        try {
            var controller = new ControllerAgencia();
            controller.abrirTelaEdicao(this);
        } catch (AgenciaException ex) {
            GerarMensagens.erro(this, ex.getMessage());
        }
    }//GEN-LAST:event_botaoEditarAgenciaActionPerformed

    private void botaoExcluirAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirAgenciaActionPerformed
        var controller = new ControllerAgencia();
        try {
            controller.excluirAgencia(this);
        } catch (AgenciaException ex) {
            GerarMensagens.erro(this, ex.getMessage());
        }
    }//GEN-LAST:event_botaoExcluirAgenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroAgencia dialog = new TelaCadastroAgencia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizaListaAgencia;
    private javax.swing.JButton botaoEditarAgencia;
    private javax.swing.JButton botaoExcluirAgencia;
    private javax.swing.JButton botaoNovaAgencia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListaAgencia;
    // End of variables declaration//GEN-END:variables
}
