/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sistemabancario.view;

import javax.swing.JTable;
import javax.swing.JTextField;
import sistemabancario.controller.ControllerTransferencia;
import sistemabancario.exception.TransferenciaException;
import sistemabancario.utils.GerarMensagens;
import sistemabancario.view.tables.TabelaTransferencia;

/**
 *
 * @author alunos
 */
public class TelaCadastroTransferencia extends javax.swing.JDialog {

    /**
     * Creates new form TelaCadastroTransferencia2
     */
    public TelaCadastroTransferencia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransferencia = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisaCpf = new javax.swing.JTextField();
        btnPesquisaCpf = new javax.swing.JButton();
        btnPesquisaGeralTransferencia = new javax.swing.JButton();
        btnNovaTransferencia = new javax.swing.JButton();
        btnExcluiTransferencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableTransferencia.setModel(new TabelaTransferencia());
        jScrollPane1.setViewportView(tableTransferencia);

        jLabel1.setText("Pesquisa por Cpf:");

        btnPesquisaCpf.setText("Pesquisar");
        btnPesquisaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaCpfActionPerformed(evt);
            }
        });

        btnPesquisaGeralTransferencia.setText("Pesquisa Geral");
        btnPesquisaGeralTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaGeralTransferenciaActionPerformed(evt);
            }
        });

        btnNovaTransferencia.setText("Nova Transferência");
        btnNovaTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaTransferenciaActionPerformed(evt);
            }
        });

        btnExcluiTransferencia.setText("Excluír");
        btnExcluiTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiTransferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPesquisaGeralTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovaTransferencia)
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisaCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(btnExcluiTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPesquisaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaCpf))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisaGeralTransferencia)
                    .addComponent(btnNovaTransferencia)
                    .addComponent(btnExcluiTransferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaCpfActionPerformed
          var controller = new ControllerTransferencia();
          controller.pesquisarCpf(this);
    }//GEN-LAST:event_btnPesquisaCpfActionPerformed

    private void btnPesquisaGeralTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaGeralTransferenciaActionPerformed
         var controller = new ControllerTransferencia();
        controller.pesquisarTodos(this);
    }//GEN-LAST:event_btnPesquisaGeralTransferenciaActionPerformed

    private void btnNovaTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaTransferenciaActionPerformed
        var TelaNovaTransferencia = new TelaNovaTransferencia(this, true);
        TelaNovaTransferencia.setVisible(true);
    }//GEN-LAST:event_btnNovaTransferenciaActionPerformed

    private void btnExcluiTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiTransferenciaActionPerformed
         var controller = new ControllerTransferencia();
        try {
            controller.excluirTransferencia(this);
        } catch (TransferenciaException ex) {
            GerarMensagens.erro(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnExcluiTransferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public JTextField getTxtPesquisaCpf() {
        return txtPesquisaCpf;
    }

    public JTable getTableTransferencia() {
        return tableTransferencia;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroTransferencia dialog = new TelaCadastroTransferencia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluiTransferencia;
    private javax.swing.JButton btnNovaTransferencia;
    private javax.swing.JButton btnPesquisaCpf;
    private javax.swing.JButton btnPesquisaGeralTransferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTransferencia;
    private javax.swing.JTextField txtPesquisaCpf;
    // End of variables declaration//GEN-END:variables
}
